---
- name: Deploy Repo
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.7

  tasks:
    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      loop:
        - nginx_1.22.1-1_amd64.deb
        - key.gen

    - name: Check nginx present
      shell:
        cmd: nginx -v 2>&1 | grep 1\.22\.1
      register: nginxPresent
      ignore_errors: true

    - name: Install Our packages
      shell:
        cmd: dpkg -i nginx_1.22.1-1_amd64.deb
      when:  nginxPresent.rc != 0 

    - name: Install tools for make repo
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - reprepro
        - dpkg-sig

    - name: Make Repo directory
      file:
        name: /var/www/repo/conf
        state: directory
        owner: root
        group: root
        mode: '1777'

    - name: Copy package description
      copy:
        src: distributions
        dest: /var/www/repo/conf/

    - name: Check public key present
      file:
        path: /var/www/repo/repo.pub.gpg.key
      register: keyPresent
      ignore_errors: true


    - name: Make gpg key
      shell:
        chdir: /var/www/repo
        cmd: gpg --batch --gen-key /home/vagrant/key.gen
      when: keyPresent.state == "absent" 

    - name: make gpg conf
      copy:
        dest: /root/.gnupg/gpg.conf
        content: digest-algo SHA256

    - name: Try make gpg key
      shell:
        chdir: /var/www/repo
        cmd: "{{ item }}"
      loop:
        - gpg --import repo.pub.gpg.key
        - dpkg-sig --sign builder /home/vagrant/nginx_1.22.1-1_amd64.deb      
        - reprepro -Vb . includedeb buster /home/vagrant/nginx_1.22.1-1_amd64.deb      

    - name: Correct nginx config
      replace:
        name: /etc/nginx/conf.d/default.conf
        replace: "\troot\t/var/www/repo;"
        regexp: '\s+root\s+.+;'
        before: "location\ =\ /50"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        


